name: Update Markdown File  # Give your workflow a clear name

on:
  push:  # Run on every push to a specific branch or branches
    branches:
      - main 
  # Or consider a schedule:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight

  workflow_dispatch: # Enable manual triggering

jobs:
  update-csv:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install dependencies (if needed)
        run: |
          python -m pip install --upgrade pip  # for Python dependencies
          pip install -r requirements.txt  # Install from a requirements file

      - name: Run code to generate markdown file
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: python main.py
        

      - uses: stefanzweifel/git-auto-commit-action@v4  # Commit and push changes
        with:
          commit_message: Update CSV file
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com 
          branch: main # reference to main